[input_files]
degreeworks_pdf_path =
graduate_study_plan_path =
four_year_schedule_path =

[output_paths]
output_excel_filename = "recommended_class_plan.xlsx"
output_directory = "outputs/"

[webcrawler]
course_catalog_url =
crawler_timeout =
crawler_max_retries =
cache_prerequisites =
prerequiste_cache_path =

[semester info]
max_semester_hours = 15
