degreeworks_pdf_path = "input/allcscourses.pdf"
graduate_study_plan_path = "input/Graduate Study Plans -revised.xlsx"
four_year_schedule_path = "input/4-year schedule.xlsx"
output_excel_filename = "recommended_class_plan.xlsx"
output_directory = "outputs/"
course_catalog_url = "https://catalog.columbusstate.edu/course-descriptions/"
cache_prerequisites = "cacheprerequisites.txt"
prerequiste_cache_path = "prerequisites.cache"
max_semester_hours = 15
#degreeworks_pdf_path = "input/4cscourses.pdf"