degreeworks_pdf_path = "degreeworks.pdf"
graduate_study_plan_path = "graduate_study_plan.pdf"
four_year_schedule_path = "four_year_schedule.pdf"
output_excel_filename = "recommended_class_plan.xlsx"
output_directory = "outputs/"
course_catalog_url = "https://catalog.columbusstate.edu/course-descriptions/"
cache_prerequisites = "cacheprerequisites.txt"
prerequiste_cache_path = "prerequisites.cache"
max_semester_hours = 15
